# Generated by Django 3.1 on 2020-10-04 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hire_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plz_name', models.CharField(max_length=10, verbose_name='이름')),
                ('plz_class', models.CharField(max_length=50, verbose_name='분야')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('date', models.DateField(verbose_name='입력 날짜')),
                ('start_date', models.DateField(verbose_name='시작 날짜')),
                ('end_date', models.DateField(verbose_name='끝 날짜')),
                ('recruit', models.DateField(verbose_name='마감일')),
                ('need_member', models.IntegerField(verbose_name='필요인원')),
                ('apply_member', models.IntegerField(verbose_name='신청인원')),
                ('timeover', models.CharField(max_length=10, verbose_name='모집여부')),
                ('plz_group', models.CharField(max_length=50, verbose_name='개인/단체')),
            ],
        ),
        migrations.CreateModel(
            name='Plus',
            fields=[
                ('plus_id', models.EmailField(max_length=100, primary_key=True, serialize=False, verbose_name='아이디')),
                ('plus_password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('plus_name', models.CharField(max_length=10, verbose_name='이름')),
                ('plus_edu', models.BooleanField(blank=True, verbose_name='교육 여부')),
                ('plus_address_small', models.CharField(max_length=100, verbose_name='주소')),
                ('plus_phonenumber', models.CharField(max_length=15, verbose_name='전화번호')),
                ('plus_talentshare', models.DateField(verbose_name='시작 날짜')),
                ('plus_start_time', models.TimeField(verbose_name='시작 시간')),
                ('plus_end_time', models.TimeField(verbose_name='끝 시간')),
                ('plus_continu_month', models.IntegerField(verbose_name='몇개월')),
                ('plus_address_big', models.CharField(max_length=10, verbose_name='행정구역')),
                ('plus_oneself', models.TextField(verbose_name='자기소개')),
                ('plus_point', models.FloatField(verbose_name='점수')),
                ('plus_class', models.CharField(max_length=50, verbose_name='분야')),
                ('plus_date', models.CharField(max_length=55, verbose_name='요일')),
                ('plus_info', models.TextField(verbose_name='한글소개')),
            ],
        ),
        migrations.CreateModel(
            name='Plz',
            fields=[
                ('plz_id', models.EmailField(max_length=100, primary_key=True, serialize=False, verbose_name='아이디')),
                ('plz_password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('plz_name', models.CharField(max_length=10, verbose_name='이름')),
                ('plz_address_small', models.CharField(max_length=100, verbose_name='주소')),
                ('plz_group', models.CharField(max_length=50, verbose_name='개인/단체')),
                ('plz_phonenumber', models.CharField(max_length=15, verbose_name='전화번호')),
                ('plz_address_big', models.CharField(max_length=10, verbose_name='행정구역')),
                ('plz_when_learn', models.CharField(max_length=50, verbose_name='희망 기간')),
                ('plz_class', models.CharField(max_length=50, verbose_name='분야')),
                ('plz_date', models.CharField(max_length=55, verbose_name='요일')),
            ],
        ),
        migrations.CreateModel(
            name='Plz_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plz_class', models.CharField(max_length=50, verbose_name='분야')),
                ('plus_name', models.CharField(max_length=10, verbose_name='이름')),
                ('plz_name', models.CharField(max_length=10, verbose_name='이름')),
                ('date', models.DateField(verbose_name='입력 날짜')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
        migrations.CreateModel(
            name='Plz_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plz_user_name', models.CharField(max_length=10, verbose_name='이름')),
                ('plz_address', models.CharField(max_length=10, verbose_name='활동분야(결국 사는곳)')),
                ('plz_class', models.CharField(max_length=50, verbose_name='분야')),
                ('plus_class', models.CharField(max_length=50, verbose_name='분야')),
                ('plus_date', models.CharField(max_length=55, verbose_name='요일')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
        migrations.CreateModel(
            name='Plus_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_name', models.CharField(max_length=10, verbose_name='이름')),
                ('plz_name', models.CharField(max_length=10, verbose_name='이름')),
                ('plus_class', models.CharField(max_length=50, verbose_name='분야')),
                ('date', models.DateField(verbose_name='입력 날짜')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('plus_point', models.FloatField(verbose_name='점수')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
        migrations.CreateModel(
            name='Plus_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_user_name', models.CharField(max_length=10, verbose_name='이름')),
                ('title', models.CharField(max_length=30, verbose_name='주제')),
                ('plus_address', models.CharField(max_length=10, verbose_name='활동분야(결국 사는곳)')),
                ('plz_class', models.CharField(max_length=50, verbose_name='분야')),
                ('plus_class', models.CharField(max_length=50, verbose_name='분야')),
                ('plus_date', models.CharField(max_length=55, verbose_name='요일')),
                ('plus_point', models.FloatField(verbose_name='점수')),
                ('hire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.hire_board')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plz_name', models.CharField(max_length=10, verbose_name='이름')),
                ('plus_name', models.CharField(max_length=10, verbose_name='이름')),
                ('plus_class', models.CharField(max_length=50, verbose_name='분야')),
                ('plz_class', models.CharField(max_length=50, verbose_name='분야')),
                ('plus_address_big', models.CharField(max_length=10, verbose_name='행정구역')),
                ('plz_address_big', models.CharField(max_length=10, verbose_name='행정구역')),
                ('match_subject', models.CharField(max_length=20, verbose_name='주제')),
                ('complete', models.BooleanField(verbose_name='완료/진행')),
                ('h_id', models.IntegerField(verbose_name='고용게시글')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
        migrations.AddField(
            model_name='hire_board',
            name='plz_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz'),
        ),
        migrations.CreateModel(
            name='Choice_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_name', models.CharField(max_length=10, verbose_name='이름')),
                ('plus_address_small', models.CharField(max_length=100, verbose_name='주소')),
                ('plus_phonenumber', models.CharField(max_length=15, verbose_name='전화번호')),
                ('plus_start_time', models.TimeField(verbose_name='시작 시간')),
                ('plus_end_time', models.TimeField(verbose_name='끝 시간')),
                ('plus_continu_month', models.IntegerField(verbose_name='몇개월')),
                ('plus_address_big', models.CharField(max_length=10, verbose_name='행정구역')),
                ('plus_point', models.FloatField(verbose_name='점수')),
                ('plus_class', models.CharField(max_length=50, verbose_name='분야')),
                ('plus_date', models.CharField(max_length=55, verbose_name='요일')),
                ('plus_info', models.TextField(verbose_name='한글소개')),
                ('plus_edu', models.BooleanField(blank=True, verbose_name='교육 여부')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
            ],
        ),
    ]
