# Generated by Django 3.1 on 2020-08-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_id', models.EmailField(max_length=100, verbose_name='아이디')),
                ('plus_password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('plus_name', models.CharField(max_length=10, verbose_name='이름')),
                ('plus_edu', models.BooleanField(blank=True, verbose_name='교육 여부')),
                ('plus_address', models.CharField(max_length=100, verbose_name='주소')),
                ('plus_has_team', models.BooleanField(blank=True, verbose_name='팀 여부')),
                ('plus_job', models.CharField(choices=[('student', '학생'), ('worker', '직장인')], max_length=7, verbose_name='직업')),
            ],
        ),
        migrations.CreateModel(
            name='Plz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plz_id', models.EmailField(max_length=100, verbose_name='아이디')),
                ('plz_password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('plz_name', models.CharField(max_length=10, verbose_name='이름')),
                ('plz_address', models.CharField(max_length=100, verbose_name='주소')),
                ('plz_group', models.BooleanField(verbose_name='개인/단체')),
            ],
        ),
        migrations.CreateModel(
            name='Plz_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='입력 날짜')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
        migrations.CreateModel(
            name='Plz_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30, verbose_name='분야')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
        migrations.CreateModel(
            name='Plus_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.IntegerField(verbose_name='인원수')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
            ],
        ),
        migrations.CreateModel(
            name='Plus_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='입력 날짜')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
        migrations.CreateModel(
            name='Plus_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, verbose_name='요일')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
            ],
        ),
        migrations.CreateModel(
            name='Plus_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30, verbose_name='분야')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_subject', models.CharField(max_length=20, verbose_name='주제')),
                ('complete', models.BooleanField(verbose_name='완료/진행')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
        migrations.CreateModel(
            name='Hire_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('date', models.DateTimeField(verbose_name='입력 날짜')),
                ('start_date', models.DateField(verbose_name='시작 날짜')),
                ('end_date', models.DateField(verbose_name='끝 날짜')),
                ('deadline', models.DateField(verbose_name='마감일')),
                ('h_number', models.IntegerField(verbose_name='필요인원')),
                ('plus_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus_class')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz_class')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
    ]
