# Generated by Django 3.1 on 2020-09-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wepler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plz',
            old_name='plz_address',
            new_name='plz_address_small',
        ),
        migrations.RenameField(
            model_name='plz',
            old_name='plz_phone',
            new_name='plz_phonenumber',
        ),
        migrations.RenameField(
            model_name='plz',
            old_name='plz_date',
            new_name='plz_when_learn',
        ),
    ]
