# Generated by Django 3.1 on 2020-08-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wepler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plus',
            old_name='plus_team',
            new_name='plus_has_team',
        ),
        migrations.CreateModel(
            name='Plus_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.IntegerField(verbose_name='인원수')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
            ],
        ),
        migrations.CreateModel(
            name='Hire_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('date', models.DateTimeField(verbose_name='입력 날짜')),
                ('start_date', models.DateTimeField(verbose_name='시작 날짜')),
                ('end_date', models.DateTimeField(verbose_name='끝 날짜')),
                ('h_number', models.IntegerField(verbose_name='필요인원')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
    ]
