# Generated by Django 3.1 on 2020-08-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wepler', '0002_auto_20200817_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plz',
            name='plz_group',
            field=models.BooleanField(verbose_name='개인/단체'),
        ),
        migrations.CreateModel(
            name='Plz_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='입력 날짜')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
        migrations.CreateModel(
            name='Plus_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='입력 날짜')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_subject', models.CharField(max_length=20, verbose_name='주제')),
                ('complete', models.BooleanField(verbose_name='완료/진행')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
                ('plz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plz')),
            ],
        ),
    ]
