# Generated by Django 3.1 on 2020-09-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepler', '0003_auto_20200911_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plz',
            name='plz_group',
            field=models.CharField(max_length=50, verbose_name='개인/단체'),
        ),
    ]
