# Generated by Django 3.1 on 2020-09-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wepler', '0004_auto_20200911_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hire_board',
            old_name='h_number',
            new_name='need_member',
        ),
        migrations.RenameField(
            model_name='hire_board',
            old_name='deadline',
            new_name='recruit',
        ),
        migrations.RemoveField(
            model_name='hire_board',
            name='plus_class',
        ),
        migrations.RemoveField(
            model_name='hire_board',
            name='plus_user',
        ),
        migrations.CreateModel(
            name='Plus_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus_class')),
                ('plus_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus_date')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepler.plus')),
            ],
        ),
    ]
